#!/bin/sh
#
# Script to run the HP Printer Application as a server.
#
# Copyright © 2022 by Michael R Sweet.
#
# Licensed under Apache License v2.0.  See the file "LICENSE" for more
# information.
#

exec $SNAP/usr/local/bin/hp-printer-app -o log-file=syslog -o log-level=info server "$@"
