#!/bin/sh
#
# makesrcdist - make a source distribution of hp-printer-app.
#

if test $# != 1; then
	echo "Usage: ./makesrcdist version"
	exit 1
fi

version=$1

echo Creating tag for release...
git tag -m "Tag $version" v$version
git push origin v$version

echo Creating hp-printer-app-$version.tar.gz...
git archive -o hp-printer-app-$version.tar.gz --prefix=hp-printer-app-$version/ HEAD
gpg --detach-sign hp-printer-app-$version.tar.gz
