name: hp-printer-app
base: core22
version: '1.3.0'
summary: HP Printer Application
description: |
  HP Printer Application is sample printer application for Hewlett Packard PCL
  (and compatible) printers.  It is based on PAPPL (Printer Application
  Framework), a simple C-based framework/library for developing CUPS Printer
  Applications, which are the recommended replacement for printer drivers.

grade: stable
confinement: strict
icon: hp-printer-app.png

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

apps:
    hp-printer-app:
        command: bin/hp-printer-app
        plugs: [avahi-control, home, network, network-bind, network-manager, raw-usb]

    hp-printer-app-server:
        command: bin/hp-printer-app-server
        daemon: simple
        plugs: [avahi-control, home, network, network-bind, network-manager, raw-usb]

hooks:
    configure:
        plugs: [avahi-control, home, network, network-bind, network-manager, raw-usb]

parts:
    libcups3:
        plugin: autotools
        autotools-configure-parameters: [--disable-shared]
        source-type: git
        source: https://github.com/OpenPrinting/libcups.git
        build-packages: [libavahi-client-dev, libssl-dev, zlib1g-dev]
        stage-packages: [libavahi-client3]

    pappl:
        plugin: autotools
        autotools-configure-parameters: [--disable-shared,--enable-libjpeg,--enable-libpng,--enable-libusb]
        source-type: git
        source: https://github.com/michaelrsweet/pappl.git
        source-branch: v1.4.x
        after: [libcups3]
        build-packages: [libavahi-client-dev, libjpeg8-dev, libpam-dev, libpng-dev, libssl-dev, libusb-1.0-0-dev, zlib1g-dev]
        stage-packages: [libavahi-client3, libjpeg8, libpng16-16, libusb-1.0-0]

    hooks:
        plugin: dump
        source: snap/local/hooks
        organize:
          configure: snap/hooks/

    scripts:
        plugin: dump
        source: snap/local/scripts
        organize:
          hp-printer-app-server: bin/

    hp-printer-app:
        plugin: autotools
        autotools-configure-parameters: [--prefix=/]
        source: .
        after: [libcups3, pappl, hooks, scripts]
